name: risunest

services:
  risunest:
    container_name: risunest
    build: .
    restart: always
    ports:
      - 6001:6001
    volumes:
      - risunest-save:/app/save

volumes:
  risunest-save:
