const english = {
    title: 'External storage',
    help: 'Encrypted incremental backups and one optional synchronization target. Transfer data stays in the native core.',
    unsupported: 'External storage is available in the Android and desktop apps.',
    add: 'Add storage', cancel: 'Cancel', refresh: 'Refresh', loading: 'Loading…',
    create: 'Create new repository', existing: 'Connect existing repository',
    backup: 'Backup only', sync: 'Synchronization', provider: 'Provider', endpoint: 'Endpoint', profile: 'Profile',
    strategy: 'Publication strategy', cas: 'CAS (concurrent-write protection)', sequential: 'Sequential use', backupOnly: 'Backup only',
    prepare: 'Review endpoint', confirmEndpoint: 'I checked this endpoint and repository', connect: 'Connect', signIn: 'Sign in', finishSignIn: 'Finish sign-in',
    pendingVerification: 'This is a local configuration check. The remote endpoint and credentials are verified only after you continue.',
    sequentialWarning: 'Use one device at a time. Confirm synchronization on one device and close it before opening another. Simultaneous use can select the wrong state as latest and may require manual recovery from retained history.',
    backupWarning: 'This destination never applies its latest state automatically.',
    githubWarning: 'I will use a dedicated private repository for these draft backup releases.',
    scope: 'Repository scope', library: 'Library and referenced assets', deviceSettings: 'Device settings', devicePlugins: 'Device plugin data',
    recoveryRequired: 'This encrypted repository needs its recovery package and code before credentials can be used.',
    recoveryPayload: 'Recovery package or QR payload', recoveryCode: 'Recovery code', unlock: 'Authenticate recovery package',
    endpointReview: 'Endpoint confirmation', authority: 'Credential authority', repository: 'Repository',
    noConnections: 'No external storage is connected.', activeSync: 'Active sync target', makeSyncTarget: 'Use for synchronization',
    runBackup: 'Back up now', runSync: 'Sync now', history: 'History', quota: 'Usage', recovery: 'Recovery key', remove: 'Remove connection',
    restore: 'Restore', download: 'Download .risunest', pin: 'Keep restore point', local: 'Keep local', remote: 'Use remote', conflicts: 'Conflicts',
    preservationPending: 'The local state is preserved. The remote state still needs to be copied before you can choose a version.', preservationComplete: 'Both states are preserved.', remotePending: 'Remote copy pending', retryPreservation: 'Retry sync preservation',
    saveRecovery: 'Save recovery file', showRecovery: 'Show recovery QR', closeRecovery: 'Hide recovery key',
    recoveryFileOnly: 'This recovery package is too large for a QR code. Save it as a file and import that file when recovering.',
    platformClientId: 'OAuth client ID for this device platform', oauthProjectHint: 'Authenticated app project',
    authorizationUnavailable: 'OAuth authorization requires a native iOS callback, which is not available in this build.',
    oneDriveAndroidSetup: 'For Android, add risunestlocal://oauth/onedrive under Mobile and desktop applications, and enable public client flows in the Entra app.',
    googleAndroidSetup: 'In Google Cloud, create a Web OAuth client, add the exact HTTPS callback URL below, and enable the Google Drive API. After sign-in, the callback page returns to RisuNest automatically.',
    webOAuthClientId: 'Web OAuth Client ID', oauthCallbackUrl: 'Registered HTTPS callback URL', oauthClientSecret: 'Client secret (optional)', manualOAuthCallback: 'Pasted callback URL (manual fallback)', manualOAuthHelp: 'If the app does not reopen automatically, paste the complete HTTPS callback URL from the callback page.',
    authorizationWaiting: 'Waiting for the browser callback. You can try again or paste the complete callback URL.', callbackRejected: 'That callback URL does not match this sign-in attempt. Check it and paste the complete URL again.',
    recoveryNotice: 'Anyone with this package and code can open the encrypted repository. Store them separately and privately.',
    completed: 'Completed', failed: 'Failed', queued: 'Queued', running: 'Working…', waiting: 'Waiting', uncertain: 'Remote result is uncertain',
    loadMore: 'Load more', statusReady: 'Ready', statusPaused: 'Paused', statusReauth: 'Sign-in required', statusLocked: 'Recovery key required', statusError: 'Needs attention',
    unknownUsage: 'Unknown', uploadedLowerBound: 'Uploaded by this app (known lower bound)', latestReachable: 'Latest reachable snapshot (incomplete lower bound)', objects: 'objects',
    invalidConfiguration: 'Check the required connection settings.', retry: 'Try again.', reauthenticate: 'Sign in again.', unlockKey: 'Unlock the repository key.', resolveRequired: 'Choose which preserved state to keep.', freeSpace: 'Free storage space and try again.',
    oldDriveNote: 'Official account Drive backup remains here. General Drive folders and other external providers are configured in RisuNest → External storage.',
}

const korean: typeof english = {
    title: '외부 저장소',
    help: '암호화된 증분 백업과 선택적인 동기화 대상 하나를 관리합니다. 전송 데이터는 네이티브 코어에서 처리됩니다.',
    unsupported: '외부 저장소는 Android 및 데스크톱 앱에서 사용할 수 있습니다.',
    add: '저장소 추가', cancel: '취소', refresh: '새로고침', loading: '불러오는 중…',
    create: '새 저장소 만들기', existing: '기존 저장소 연결',
    backup: '백업 전용', sync: '동기화', provider: '공급자', endpoint: '엔드포인트', profile: '프로필',
    strategy: '게시 방식', cas: 'CAS (동시 쓰기 보호)', sequential: '순차 사용', backupOnly: '백업 전용',
    prepare: '엔드포인트 검토', confirmEndpoint: '이 엔드포인트와 저장소를 확인했습니다', connect: '연결', signIn: '로그인', finishSignIn: '로그인 완료',
    pendingVerification: '현재는 로컬 설정만 검사합니다. 원격 엔드포인트와 자격 증명은 계속 진행한 뒤 검증됩니다.',
    sequentialWarning: '한 번에 기기 하나만 사용하세요. 한 기기에서 동기화 완료를 확인하고 종료한 뒤 다른 기기를 여세요. 동시에 사용하면 다른 상태가 최신으로 선택될 수 있고 보존된 이력에서 수동 복구해야 할 수 있습니다.',
    backupWarning: '이 목적지는 최신 상태를 자동으로 적용하지 않습니다.',
    githubWarning: '초안 백업 릴리스 전용 비공개 저장소를 사용합니다.',
    scope: '저장소 범위', library: '라이브러리와 참조 자산', deviceSettings: '기기 설정', devicePlugins: '기기 플러그인 데이터',
    recoveryRequired: '암호화된 기존 저장소는 자격 증명을 보내기 전에 복구 패키지와 코드가 필요합니다.',
    recoveryPayload: '복구 패키지 또는 QR 내용', recoveryCode: '복구 코드', unlock: '복구 패키지 인증',
    endpointReview: '엔드포인트 확인', authority: '자격 증명 대상', repository: '저장소',
    noConnections: '연결된 외부 저장소가 없습니다.', activeSync: '활성 동기화 대상', makeSyncTarget: '동기화 대상으로 사용',
    runBackup: '지금 백업', runSync: '지금 동기화', history: '이력', quota: '사용량', recovery: '복구 키', remove: '연결 삭제',
    restore: '복원', download: '.risunest 다운로드', pin: '복원 지점 유지', local: '로컬 유지', remote: '원격 사용', conflicts: '충돌',
    preservationPending: '로컬 상태는 보존되었습니다. 유지할 버전을 선택하려면 원격 상태 복사를 완료해야 합니다.', preservationComplete: '두 상태가 모두 보존되었습니다.', remotePending: '원격 복사 대기 중', retryPreservation: '동기화 보존 다시 시도',
    saveRecovery: '복구 파일 저장', showRecovery: '복구 QR 표시', closeRecovery: '복구 키 숨기기',
    recoveryFileOnly: '이 복구 패키지는 QR 코드 용량을 초과합니다. 파일로 저장하고 복구할 때 해당 파일을 가져오세요.',
    platformClientId: '이 기기 플랫폼용 OAuth 클라이언트 ID', oauthProjectHint: '인증된 앱 프로젝트',
    authorizationUnavailable: 'OAuth 인증에는 네이티브 iOS 콜백이 필요하지만 이 빌드에서는 사용할 수 없습니다.',
    oneDriveAndroidSetup: 'Android에서는 Entra 앱의 모바일 및 데스크톱 애플리케이션에 risunestlocal://oauth/onedrive를 추가하고 공용 클라이언트 흐름을 사용 설정하세요.',
    googleAndroidSetup: 'Google Cloud에서 웹 OAuth 클라이언트를 만들고 아래의 정확한 HTTPS 콜백 URL을 추가한 뒤 Google Drive API를 사용 설정하세요. 로그인 후 콜백 페이지가 자동으로 RisuNest로 돌아옵니다.',
    webOAuthClientId: '웹 OAuth 클라이언트 ID', oauthCallbackUrl: '등록된 HTTPS 콜백 URL', oauthClientSecret: '클라이언트 보안 비밀 (선택 사항)', manualOAuthCallback: '붙여넣은 콜백 URL (수동 대체 경로)', manualOAuthHelp: '앱이 자동으로 다시 열리지 않으면 콜백 페이지의 전체 HTTPS 콜백 URL을 붙여넣으세요.',
    authorizationWaiting: '브라우저 콜백을 기다리는 중입니다. 다시 시도하거나 전체 콜백 URL을 붙여넣을 수 있습니다.', callbackRejected: '이 콜백 URL은 현재 로그인 시도와 일치하지 않습니다. 확인한 뒤 전체 URL을 다시 붙여넣으세요.',
    recoveryNotice: '이 패키지와 코드를 가진 사람은 암호화된 저장소를 열 수 있습니다. 둘을 분리하여 안전하게 보관하세요.',
    oldDriveNote: '공식 계정 Drive 백업은 이 위치에 유지됩니다. 일반 Drive 폴더와 다른 외부 공급자는 RisuNest → 외부 저장소에서 설정하세요.',
    completed: '완료', failed: '실패', queued: '대기열에 추가됨', running: '처리 중…', waiting: '대기 중', uncertain: '원격 결과를 확인할 수 없음',
    loadMore: '더 불러오기', statusReady: '사용 가능', statusPaused: '일시 중지됨', statusReauth: '다시 로그인해야 함', statusLocked: '복구 키 필요', statusError: '확인 필요',
    unknownUsage: '알 수 없음', uploadedLowerBound: '이 앱에서 업로드함 (확인된 최솟값)', latestReachable: '최신 접근 가능 스냅샷 (불완전한 최솟값)', objects: '개 객체',
    invalidConfiguration: '필수 연결 설정을 확인하세요.', retry: '다시 시도하세요.', reauthenticate: '다시 로그인하세요.', unlockKey: '저장소 키 잠금을 해제하세요.', resolveRequired: '보존된 상태 중 유지할 항목을 선택하세요.', freeSpace: '저장 공간을 확보한 뒤 다시 시도하세요.',
}

export type ExternalStorageStrings = typeof english

export function externalStorageStrings(languageCode: string): ExternalStorageStrings {
    return languageCode === 'ko' ? korean : english
}
